version: '3.8'

services:
  frontend-react:
    build: .
    container_name: donaton-react-app
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3000
